name: cli_template
description: A sample command-line application with basic argument parsing.
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  args: ^2.4.2
  dcli: ^6.0.5
  cli_util: ^0.4.1
  cli_menu: ^0.4.0+1
  cli_spin: ^1.0.1
  cli_table: ^1.0.2
  cli_config: ^0.2.0
  cli_completion: ^0.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
