name: project_state
description: Project contain application state
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: 8.1.4
  mocktail: 1.0.4
  flutter_bloc: 8.1.6
  freezed_annotation: 2.4.4

  project_data:
    path: ../project_data
  project_repository:
    path: ../project_repository

dev_dependencies:
  build_runner: 2.4.11
  bloc_test: 9.1.7
  freezed: 2.5.2
  lints: 4.0.0
  test: 1.24.0
