name: project_state
description: Project contain application state
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  bloc: 8.1.4
  equatable: 2.0.5
  flutter_bloc: 8.1.6

  project_data:
    path: ../project_data
  project_repository:
    path: ../project_repository

dev_dependencies:
  bloc_test: 9.1.7
  lints: 4.0.0
  test: 1.24.0
