name: project_repository
description: Obtain data from various data sources
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: 5.5.0+1
  mocktail: 1.0.4
  auto_injector: 2.0.5
  flutter_secure_storage: 9.2.2
  internet_connection_checker: 1.0.0+1

  project_common:
    path: ../project_common
  project_data:
    path: ../project_data

dev_dependencies:
  lints: 4.0.0
  test: 1.24.0
