name: project_common
description: Project contain common project tools
version: 0.1.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  talker: <=4.1.2             # Upgrade to higher version only after upgrade Java SDK to version 17
  talker_dio_logger: <=4.1.2  # Upgrade to higher version only after upgrade Java SDK to version 17

dev_dependencies:
  lints: 4.0.0
  test: 1.24.0
